version: 2.1

parameters:
  checking:
    type: boolean
    default: true
  doing:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: node:latest

jobs:
  build:
    executor: node
    steps:
      - run: checkout
      - run: echo "build step"
  publish-github-release:
    executor: node
      - run:
          name: "Publish Release on GitHub"
          command: |
            curl -f --show-error --location --request POST 'https://circleci.com/api/v2/project/gh/annapamma/sandbox/pipeline' \
            --header 'Content-Type: application/json' \
            --header "Circle-Token: ${CIRCLE_TOKEN}" \
            --header 'Accept: application/json' \
            -d '{
                "parameters": {
                    "checking": false,
                    "doing": true
                }
            }
            '
#            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
      # https://circleci.com/blog/publishing-to-github-releases-via-circleci/
  do_stuff:
    executor: node
    steps:
      - run: echo "did stuff"

workflows:
  check_stuff:
    when: << pipeline.parameters.checking >>
    jobs:
      - check_stuff
  do_stuff:
    when: << pipeline.parameters.doing >>
    jobs:
      - do_stuff


# This pipeline needs to:
# - Create a tag
## is this a GH tag or an internal tag?
# - Delete a branch
# - Auto increment environment variable