version: 2.1

parameters:
  build_and_publish:
    type: boolean
    default: true
  delete_branch:
    type: boolean
    default: false
  branch_to_delete:
    type: string
    default: ''

executors:
  node:
    docker:
      - image: node:latest

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: echo "build step"
      - run: echo "store artifacts from build step"
  unit-test:
    executor: node
    steps:
      - checkout
      - run: echo "testing"
  e2e-test:
    executor: node
    steps:
      - checkout
      - run: echo "testing"
  lint:
    executor: node
    steps:
      - checkout
      - run: echo "testing"
  hold-for-release:
    executor: node
    steps:
      - run: echo "holding"
  publish-github-release:
    executor: node
    steps:
      - checkout
      - run: echo "ghr command"
      - run: echo "trigger branch cleanup"
  delete-branch:
    executor: node
    steps:
      - checkout
      - run: echo "delete branch here"
      - run: echo "auto increment version here, by maintaining it in project variables"

workflows:
  publish-github-release:
    when: << pipeline.parameters.build_and_publish >>
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - e2e-test:
          requires:
            - build
      - lint:
          requires:
            - build
      - hold-for-release:
          type: approval
      - publish-github-release:
          requires:
            - hold-for-release
      - delete-branch:
          requires:
            - publish-github-release

# This pipeline needs to:
# - Create a tag
# - Delete a branch
# - Auto increment environment variable

#
#HELPFUL DOCS:
# github release with CCI: https://circleci.com/blog/publishing-to-github-releases-via-circleci/
