version: 2.1

parameters:
  build_and_publish:
    type: boolean
    default: true
  delete_branch:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: node:latest

jobs:
  build:
    executor: node
    steps:
      - run: checkout
      - run: echo "build step"
  # add artifact storage step
  test:
    executor: node
    steps:
      - run: checkout
      - run: echo "testing"
  publish-github-release:
    executor: node
    steps:
      - run:
          name: "Publish Release on Github"
          command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
      # https://circleci.com/blog/publishing-to-github-releases-via-circleci/
      - run:
          name: "Trigger branch cleanup"
          command: |
            curl -f --show-error --location --request POST 'https://circleci.com/api/v2/project/gh/annapamma/tpi-sandbox/pipeline' \
            --header 'Content-Type: application/json' \
            --header "Circle-Token: ${CIRCLE_TOKEN}" \
            --header 'Accept: application/json' \
            -d '{
                "parameters": {
                    "build_and_publish": false,
                    "delete_branch": true
                }
            }
            '
  do_stuff:
    executor: node
    steps:
      - run: echo "did stuff"

workflows:
  publish-github-release:
    when: << pipeline.parameters.build_and_publish >>
    jobs:
      - build
      - test:
          requires:
            - build
      - publish-github-release
  delete_branch:
    when: << pipeline.parameters.delete_branch >>
    jobs:
      - do_stuff


# This pipeline needs to:
# - Create a tag
## is this a GH tag or an internal tag?
# - Delete a branch
# - Auto increment environment variable